version: '3.8'

services:
  web_api:
    build:
      context: . # Assumes docker-compose.yml is in the ai_scraper_framework directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mounts the current directory (ai_scraper_framework) on the host
      # to /app in the container. This allows for live reloading.
      - ./:/app
    command: uvicorn ai_scraper_framework.api.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - APP_ENV=development # For ConfigurationManager to load development.yaml
      # PLAYWRIGHT_BROWSERS_PATH: /ms-playwright # Optional: if browsers are installed in a non-default path within the container
      # (though `playwright install` should handle this by default in /root/.cache/ms-playwright or similar user-specific path)
    # depends_on: # Example if we had a database service
      # - db
    # networks: # Example if we had custom networks
      # - app_network

# networks: # Example
  # app_network:
    # driver: bridge

# volumes: # Example if we needed named volumes for persistent data
  # db_data:
