database:
  engine: postgresql+asyncpg # DSN scheme
  host: db # Service name in docker-compose for development
  port: 5432
  username: ai_scraper_user
  password: ai_scraper_password # Ensure this matches docker-compose and local dev setup if any
  dbname: ai_scraper_db
  echo: true # Log SQL queries in dev
  pool_size: 5 # Existing value

redis: # Placeholder, not used yet
  host: localhost
  port: 6379
  db: 0

# Top-level 'models' key is being deprecated in favor of component-specific model configs.
models: 
  confidence_threshold: 0.7 
  batch_size: 8            

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(funcName)s:%(lineno)d - %(message)s"
  handlers:
    console:
      enabled: true
    file:
      enabled: true
      path: "logs/ai_scraper_dev.log"
      max_bytes: 10485760 # 10MB
      backup_count: 5

components:
  playwright_manager:
    browser_type: "chromium"
  file_storage: # FileStorage might still be used for temporary files or non-DB storage
    base_path: "scraped_data_refined_dev"
  vision:
    yolo_model_path: "models/cv_models/yolov8n.pt" 
  extractor:
    spacy_model_name: "en_core_web_sm"

scraping: # General scraping parameters
  max_concurrent_requests: 5
  request_delay: 2.0
  timeout: 30 
  retry_attempts: 3
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
