# TODO: Replace placeholder values with actual production configuration and manage secrets appropriately.
database:
  engine: postgresql+asyncpg # DSN scheme
  host: "YOUR_PROD_DB_HOST"    # e.g., from environment variable or secrets manager
  port: 5432
  username: "YOUR_PROD_DB_USER"
  password: "YOUR_PROD_DB_PASSWORD" # Managed via secrets
  dbname: "ai_scraper_prod_db" # Or your specific production DB name
  echo: false # Typically false for production
  pool_size: 20 # Existing value

redis: # Placeholder
  host: prod_redis_host
  port: 6379
  db: 0

models: # This top-level 'models' key might be deprecated.
  confidence_threshold: 0.85 
  batch_size: 16             

logging:
  level: WARNING 
  format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(funcName)s:%(lineno)d - %(message)s"
  handlers:
    console:
      enabled: true 
    file:
      enabled: true
      path: "logs/ai_scraper_prod.log" 
      max_bytes: 104857600 # 100MB
      backup_count: 10

components:
  playwright_manager:
    browser_type: "chromium" 
  file_storage: # Still useful for temporary files or non-DB outputs
    base_path: "/app/storage/prod_file_outputs" # Example absolute path for production
  vision:
    yolo_model_path: "/app/models/cv_models/yolov8_prod_model.pt" 
  extractor:
    spacy_model_name: "en_core_web_lg" 

scraping: 
  max_concurrent_requests: 20
  request_delay: 0.5 
  timeout: 60
  retry_attempts: 5
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
